"""Merge the research dossiers' bibliographies into one, canonicalising keys.

Four dossiers cite overlapping literature, so the same work appears under
different keys.  Merging naively produces duplicate-key errors at build time and,
worse, two entries for one paper that a reader cannot tell apart.  The merge keeps
the first definition of each key and reports collisions where two different works
claim one key.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
REFS = ROOT / "spec" / "background" / "refs"
OUT = ROOT / "paper" / "refs.bib"

ENTRY = re.compile(r"@(\w+)\s*\{\s*([^,]+),", re.M)


def entries(text: str):
    starts = [(m.start(), m.group(1).lower(), m.group(2).strip()) for m in ENTRY.finditer(text)]
    for i, (start, kind, key) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(text)
        yield key, kind, text[start:end].rstrip()


def main() -> None:
    seen: dict[str, str] = {}
    collisions: list[str] = []
    sources: dict[str, str] = {}
    for path in sorted(REFS.glob("*.bib")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for key, _kind, body in entries(text):
            norm = re.sub(r"[^a-zA-Z0-9]", "", key).lower()
            if norm in seen:
                if _title(body) != _title(seen[norm]):
                    collisions.append(f"{key} ({path.name} vs {sources[norm]})")
                continue
            # Drop the dossiers' annotation notes.  They are valuable provenance
            # and stay in spec/background/refs/, but in a reference list they are noise:
            # a reader wants the citation, not our reading notes on it.
            seen[norm] = re.sub(
                r",\s*note\s*=\s*\{(?:[^{}]|\{[^{}]*\})*\}", ",", body, flags=re.S
            )
            sources[norm] = path.name
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "% Generated by paper/tools/build_bib.py from spec/background/refs/*.bib.\n"
        f"% {len(seen)} unique entries merged from {len(list(REFS.glob('*.bib')))} dossiers.\n\n"
        + "\n\n".join(seen[k] for k in sorted(seen))
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}: {len(seen)} entries")
    if collisions:
        print(f"key collisions with differing titles ({len(collisions)}):")
        for c in collisions[:20]:
            print("  ", c)


def _title(body: str) -> str:
    m = re.search(r"title\s*=\s*[{\"](.+?)[}\"]\s*,", body, re.S | re.I)
    return re.sub(r"\s+", " ", m.group(1)).strip().lower() if m else ""


if __name__ == "__main__":
    main()
