#!/usr/bin/env python3
"""Consolidate the BibTeX blocks emitted by the literature-survey notes.

Each file in ``paper/research/`` ends with a ``## BibTeX`` section. Several were
written independently, so keys collide and entries differ in completeness. This
script merges them, preferring the entry with the most fields for any duplicated
key, and reports collisions where two entries share a key but disagree about the
title -- those are genuine conflicts a human must resolve before submission.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

ENTRY_RE = re.compile(r"@(\w+)\s*\{\s*([^,\s]+)\s*,", re.MULTILINE)

#: Works that arrived under two keys because they were surveyed independently.
#: The value is the key we keep; the alias is dropped and any citation of it is
#: rewritten by `canonical_key`. Resolving these by hand is correct: an automatic
#: title match would also merge genuinely distinct editions of the same standard.
ALIASES = {
    "carriero1989linda": "carriero1989lindaincontext",
    "mpi22": "mpiforum2009mpi22",
    "mpi31": "mpiforum2015mpi31",
    "mpi41": "mpiforum2023mpi41",
    "mpi50": "mpiforum2025mpi50",
    "flp1985impossibility": "fischer1985impossibility",
    "kleppmann2016locks": "kleppmann2016locking",
}


def canonical_key(key: str) -> str:
    return ALIASES.get(key, key)


def split_entries(text: str) -> List[Tuple[str, str, str]]:
    """Return (kind, key, source) for each BibTeX entry, brace-balanced."""
    out: List[Tuple[str, str, str]] = []
    for m in ENTRY_RE.finditer(text):
        start = m.start()
        depth = 0
        i = text.index("{", start)
        for j in range(i, len(text)):
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
                if depth == 0:
                    out.append((m.group(1).lower(), m.group(2), text[start : j + 1]))
                    break
    return out


def field_count(src: str) -> int:
    return len(re.findall(r"^\s*\w+\s*=", src, re.MULTILINE))


def title_of(src: str) -> str:
    m = re.search(r"title\s*=\s*[{\"](.+?)[}\"]\s*,?\s*$", src, re.MULTILINE | re.DOTALL)
    if not m:
        return ""
    return re.sub(r"[\s{}]+", " ", m.group(1)).strip().lower()[:90]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--research", default="paper/research")
    ap.add_argument("--out", default="paper/refs.bib")
    args = ap.parse_args()

    best: Dict[str, Tuple[str, str, str]] = {}
    seen_titles: Dict[str, List[Tuple[str, str]]] = defaultdict(list)
    per_file: Dict[str, int] = {}
    sources = list(sorted(Path(args.research).glob("*.md")))
    extra = Path(args.out).with_name("refs-extra.bib")
    if extra.exists():
        sources.append(extra)
    for path in sources:
        text = path.read_text(encoding="utf-8", errors="replace")
        if path.suffix == ".bib":
            block = text
        else:
            idx = text.rfind("## BibTeX")
            block = text[idx:] if idx >= 0 else text
        entries = split_entries(block)
        per_file[path.name] = len(entries)
        for kind, key, src in entries:
            key = canonical_key(key)
            src = re.sub(r"(@\w+\s*\{\s*)[^,\s]+(\s*,)", r"\g<1>" + key + r"\g<2>", src, count=1)
            prev = best.get(key)
            if prev is None or field_count(src) > field_count(prev[2]):
                best[key] = (kind, key, src)
            t = title_of(src)
            if t:
                seen_titles[key].append((t, path.name))

    conflicts = []
    for key, ts in seen_titles.items():
        distinct = {t for t, _ in ts}
        if len(distinct) > 1:
            conflicts.append((key, sorted(distinct)))

    dup_titles: Dict[str, List[str]] = defaultdict(list)
    for key, (_, _, src) in best.items():
        t = title_of(src)
        if t:
            dup_titles[t].append(key)
    alias = {t: ks for t, ks in dup_titles.items() if len(ks) > 1}

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "% AgentMPI bibliography.",
        "% Generated by scripts/build_bib.py from the literature-survey notes in",
        "% paper/research/. Do not edit by hand: edit the notes and regenerate.",
        f"% {len(best)} unique keys from {len(per_file)} survey files.",
        "",
    ]
    body = "\n\n".join(best[k][2] for k in sorted(best))
    out.write_text("\n".join(header) + body + "\n", encoding="utf-8")

    print(f"wrote {out} with {len(best)} entries")
    for f, n in sorted(per_file.items()):
        print(f"  {f}: {n} entries")
    if conflicts:
        print(f"\n{len(conflicts)} KEY CONFLICTS (same key, different titles) -- resolve before submission:")
        for key, titles in conflicts[:15]:
            print(f"  {key}:")
            for t in titles:
                print(f"    - {t}")
    if alias:
        print(f"\n{len(alias)} DUPLICATE WORKS under different keys:")
        for t, ks in list(alias.items())[:15]:
            print(f"  {', '.join(ks)}  <- {t}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
