#!/usr/bin/env python3
"""Emit LaTeX macros for every number the paper quotes.

No measured number is typed into the paper by hand. Each one becomes a macro
defined here from the results JSON, so regenerating the benchmarks regenerates
the paper's claims, and a claim that has no supporting measurement fails loudly
at compile time (the macro is undefined) instead of quietly going stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


def fmt(v: Any, digits: int = 0) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, str):
        return v
    if isinstance(v, float) and digits > 0:
        return f"{v:.{digits}f}"
    if isinstance(v, float) and v == int(v):
        v = int(v)
    if isinstance(v, int) and abs(v) >= 10000:
        s = f"{v:,}"
        return s.replace(",", "{,}")
    if isinstance(v, float):
        return f"{v:.3g}"
    return str(v)


class Macros:
    def __init__(self) -> None:
        self.lines: List[str] = []
        self.names: set[str] = set()

    def add(self, name: str, value: Any, digits: int = 0) -> None:
        assert name not in self.names, f"duplicate macro {name}"
        self.names.add(name)
        self.lines.append(rf"\newcommand{{\{name}}}{{{fmt(value, digits)}\xspace}}")

    def raw(self, name: str, body: str) -> None:
        assert name not in self.names, f"duplicate macro {name}"
        self.names.add(name)
        self.lines.append(rf"\newcommand{{\{name}}}{{{body}\xspace}}")

    def text(self) -> str:
        head = [
            "% Generated by scripts/make_macros.py -- do not edit.",
            "% Every measured number in the paper comes from here.",
            r"\providecommand{\xspace}{}",
            "",
        ]
        return "\n".join(head + sorted(self.lines)) + "\n"


def pick(rows: List[Dict[str, Any]], **kw: Any) -> Optional[Dict[str, Any]]:
    for r in rows:
        if all(r.get(k) == v for k, v in kw.items()):
            return r
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--microbench", default="results/microbench.json")
    ap.add_argument("--e1", default="results/e1_metrics.json")
    ap.add_argument("--e2", default="results/e2_grade.json")
    ap.add_argument("--e3", default="results/e3_metrics.json")
    ap.add_argument("--e2b", default="results/e2_behaviour.json")
    ap.add_argument("--out", default="paper/results.tex")
    args = ap.parse_args()
    m = Macros()

    mb_path = Path(args.microbench)
    if mb_path.exists():
        mb = json.loads(mb_path.read_text())
        m.raw("tokenEstimator", mb["token_estimator"].replace("_", r"\_"))
        s = mb["suites"]

        if "latency" in s:
            fit = s["latency"]["fit_eager"]
            m.add("alphaMs", (fit["alpha_s"] or 0) * 1e3, 1)
            m.add("betaUsPerTok", (fit["beta_s_per_token"] or 0) * 1e6, 2)
            m.add("nHalfTokens", int(round(fit["n_half_tokens"] or 0)))
            m.add("latencyReps", s["latency"]["reps"])

        if "collectives" in s:
            rows = s["collectives"]["rows"]
            ps = s["collectives"]["P_sweep"]
            m.add("collMaxP", max(ps))
            m.add("collPayloadTokens", s["collectives"]["payload_tokens"])
            big = max(ps)
            rd = pick(rows, op="allreduce", algo="recursive_doubling", P=big)
            rb = pick(rows, op="allreduce", algo="reduce_bcast", P=big)
            if rd and rb:
                m.add("arRdTokens", rd["message_tokens"])
                m.add("arRbTokens", rb["message_tokens"])
                m.add("arRdRatio", rd["message_tokens"] / max(1, rb["message_tokens"]), 1)
                m.add("arRdMsgs", rd["messages"])
                m.add("arRbMsgs", rb["messages"])
            ring = pick(rows, op="allgather", algo="ring", P=big)
            agrd = pick(rows, op="allgather", algo="recursive_doubling", P=big)
            if ring and agrd:
                m.add("agRingMsgs", ring["messages"])
                m.add("agRingTokens", ring["message_tokens"])
                m.add("agRdMsgs", agrd["messages"])
                m.add("agRdTokens", agrd["message_tokens"])
                m.add("agRingRatio", ring["message_tokens"] / max(1, agrd["message_tokens"]), 1)

        if "scaling" in s:
            sc = s["scaling"]["rows"]
            # TeX macro names are letters only, so no digits in these names.
            for P, tag in ((32, "Mid"), (128, "High")):
                c = pick(sc, op="barrier", algo="central", P=P)
                d = pick(sc, op="barrier", algo="dissemination", P=P)
                if c:
                    m.add(f"barCentral{tag}", c["wall_s"], 2)
                    m.add(f"barP{tag}", P)
                if d:
                    m.add(f"barDissem{tag}", d["wall_s"], 2)
            ar = s["scaling"].get("agent_reduce") or []
            if ar:
                m.add("mergeCostS", ar[0]["merge_cost_s"], 2)
                big = max(r["P"] for r in ar)
                b = pick(ar, P=big, algo="binomial")
                ch = pick(ar, P=big, algo="chain")
                if b:
                    m.add("agentRedP", big)
                    m.add("agentRedBinDepth", b["predicted_serial_depth"])
                    m.add("agentRedBinMaxPerRank", b["max_merges_per_rank"])
                    m.add("agentRedBinTotal", b["merges_total"])
                    m.add("agentRedBinWall", b["wall_s"], 2)
                    m.add("agentRedBinEffDepth", b["effective_serial_depth"], 1)
                if ch:
                    m.add("agentRedChainDepth", ch["predicted_serial_depth"])
                    m.add("agentRedChainTotal", ch["merges_total"])
                    m.add("agentRedChainWall", ch["wall_s"], 2)
                    m.add("agentRedChainEffDepth", ch["effective_serial_depth"], 1)
                if b and ch and b["wall_s"]:
                    m.add("agentRedSpeedup", ch["wall_s"] / b["wall_s"], 1)
                exact = [r for r in ar if r["algo"] == "binomial"
                         and r["max_merges_per_rank"] == r["predicted_serial_depth"]]
                m.add("agentRedExactMatches", len(exact))
                m.add("agentRedBinPoints", len([r for r in ar if r["algo"] == "binomial"]))

        if "context" in s:
            rows = s["context"]["rows"]
            P = s["context"]["P"]
            m.add("ctxP", P)
            m.add("ctxPayloadTokens", rows[0]["payload_tokens"])
            for op in ("bcast", "allgather"):
                for disc, tag in (("inline", "Inline"), ("handle", "Handle"),
                                  ("view400", "View")):
                    r = pick(rows, op=op, discipline=disc)
                    if not r:
                        continue
                    nm = op.replace("allgather", "Ag").replace("bcast", "Bc")
                    m.add(f"ctx{nm}{tag}Total", r["total_context_tokens"])
                    m.add(f"ctx{nm}{tag}Peak", r["per_rank_hwm"]["max"])
            ai = pick(rows, op="allgather", discipline="inline")
            ah = pick(rows, op="allgather", discipline="handle")
            if ai and ah and ah["per_rank_hwm"]["max"]:
                m.add("ctxAgPeakRatio",
                      ai["per_rank_hwm"]["max"] / ah["per_rank_hwm"]["max"], 0)
                m.add("ctxAgTotalRatio",
                      ai["total_context_tokens"] / max(1, ah["total_context_tokens"]), 0)

        if "matching" in s:
            rows = s["matching"]["rows"]
            m.add("matchMaxDepth", max(r["queue_depth"] for r in rows))
            lo = pick(rows, queue_depth=0)
            hi = max(rows, key=lambda r: r["queue_depth"])
            if lo:
                m.add("matchMedianEmpty", lo["recv_s"]["p50"] * 1e3, 2)
            m.add("matchMedianDeep", hi["recv_s"]["p50"] * 1e3, 2)

    # ---- experiment 1 -----------------------------------------------------
    e1p = Path(args.e1)
    if e1p.exists():
        e1 = json.loads(e1p.read_text())
        for arm in ("ampi", "naive"):
            a = e1["arms"].get(arm)
            if not a:
                continue
            tag = "Ampi" if arm == "ampi" else "Naive"
            m.add(f"eOne{tag}P", a["np"])
            m.add(f"eOne{tag}Completion", a["coverage"]["completion"], 2)
            m.add(f"eOne{tag}Modal", a["terminology"]["mean_modal_share"], 3)
            m.add(f"eOne{tag}FullyConsistent",
                  a["terminology"]["fully_consistent_fraction"], 3)
            m.add(f"eOne{tag}Distinct", a["terminology"]["mean_distinct_renderings"], 2)
            m.add(f"eOne{tag}TermsScored", a["terminology"]["terms_scored"])
            m.add(f"eOne{tag}PeakCtx", a["protocol"]["context"]["hwm"]["max"])
            m.add(f"eOne{tag}TotalCtx", a["protocol"]["context"]["total_delivered_tokens"])
            m.add(f"eOne{tag}Wall", a["protocol"]["wall_s"], 0)
            m.add(f"eOne{tag}Retries", a["protocol"]["timeout_retries_total"])
            m.add(f"eOne{tag}Msgs", a["protocol"]["messages"]["count"])
            m.add(f"eOne{tag}CjkChars", a["coverage"]["cjk_chars_total"])
        a = e1["arms"].get("ampi")
        if a:
            g = a["glossary"]
            m.add("eOneMergeTotal", g.get("merge_steps_total"))
            m.add("eOneMergeCrit", g.get("merge_steps_critical_path"))
            m.add("eOneAdherence", g.get("adherence"), 3)
            m.add("eOneGlossaryTerms", g.get("agreed_glossary_terms"))
            m.add("eOneRevised", a["boundary"]["drafts_revised_after_halo"])
            m.add("eOneRevisionRate", a["boundary"]["revision_rate"], 2)
        cmp_ = e1.get("comparison") or {}
        if cmp_:
            m.add("eOneModalGain",
                  cmp_["terminology_mean_modal_share"].get("absolute_gain"), 3)
            m.add("eOnePeakCtxRatio",
                  cmp_["peak_rank_context_tokens"].get("ratio_naive_over_ampi"), 1)

    # ---- experiment 2 -----------------------------------------------------
    # Arms that were not run still get macros, valued "n/a", so that the paper
    # compiles from partial data with an honest gap rather than failing to build
    # or, worse, silently omitting a column.
    E2_CATS = ("reader", "special", "tailcall", "numeric", "list", "equality",
               "string", "vector", "error", "integration")
    e2p = Path(args.e2)
    e2 = json.loads(e2p.read_text()) if e2p.exists() else {"arms": {}}
    # The suite size is a static property of the grading suite, so read it from
    # the suite itself rather than waiting for a run to report it.
    suite_size = e2.get("suite_size")
    if suite_size is None:
        try:
            sys.path.insert(0, str(Path(__file__).resolve().parent.parent
                                   / "experiments" / "e2_codev"))
            import grade as _grade  # type: ignore

            suite_size = len(_grade.CASES)
        except Exception:
            suite_size = None
    m.add("eTwoSuite", suite_size)
    for arm, tag in (("ampi", "Ampi"), ("naive", "Naive")):
        a = (e2.get("arms") or {}).get(arm)
        m.add(f"eTwo{tag}Pass", a["passed"] if a else None)
        m.add(f"eTwo{tag}Rate", (a["pass_rate"] if a else None), 3)
        for cat in E2_CATS:
            d = (a or {}).get("by_category", {}).get(cat)
            m.add(f"eTwo{tag}{cat.capitalize()}", (d["pass_rate"] if d else None), 2)

    # ---- experiment 2, behaviour and cost ---------------------------------
    e2b = Path(args.e2b)
    if e2b.exists():
        for k, v in (json.loads(e2b.read_text()).get("macros") or {}).items():
            m.add(k, v)

    # ---- experiment 3 -----------------------------------------------------
    e3p = Path(args.e3)
    if e3p.exists():
        e3 = json.loads(e3p.read_text())
        for k, v in (e3.get("macros") or {}).items():
            m.add(k, v)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(m.text(), encoding="utf-8")
    print(f"wrote {out} with {len(m.names)} macros")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
